# Generated by Django 3.2 on 2024-11-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referall_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referalluser',
            name='username',
            field=models.CharField(blank=True, help_text='Укажите имя пользователя', max_length=150, null=True, verbose_name='Имя пользователя'),
        ),
    ]
